window.PHAT_GORRILLA_PRODUCTS = [
  {
    "id": "6a1a9c3b1babc69aaa0ed446",
    "title": "Phat Gorrilla Gold Logo Tee",
    "visible": true,
    "price_from": "£27.99",
    "price_to": "£27.99",
    "image": "https://images-api.printify.com/mockup/6a1a9c3b1babc69aaa0ed446/11962/102005/tshirt-phat-gorilla-gold-logo-tee.jpg?camera_label=front-2",
    "buy_url": "/.netlify/functions/create-checkout-session?key=t-shirt-phat-gorilla-gold-logo-tee-11962",
    "drop": "Main Drop",
    "type": "T-Shirt",
    "colours": "Black / Gold",
    "sizes": "Sizes shown at checkout",
    "offer": "A clean gold-logo streetwear tee for the core Phat Gorrilla look. Secure GBP checkout, printed and fulfilled by Printify. Full app access comes free after purchase."
  },
  {
    "id": "6a1bd5d199790633660760e0",
    "title": "Scotland Phat Gorrilla World Cup Tee",
    "visible": true,
    "price_from": "£27.99",
    "price_to": "£27.99",
    "image": "https://images-api.printify.com/mockup/6a1bd5d199790633660760e0/12124/92570/scotland-phat-gorrilla-world-cup-tee-gildan-5000.jpg?camera_label=front",
    "buy_url": "/.netlify/functions/create-checkout-session?key=scotland-phat-gorrilla-world-cup-tee-gildan-5000-11956",
    "drop": "World Cup",
    "type": "T-Shirt",
    "colours": "Scotland colours",
    "sizes": "Sizes shown at checkout",
    "offer": "Built for bold Scotland supporters with intentional rustic print texture and Phat Gorrilla energy. Secure GBP checkout, printed and fulfilled by Printify."
  },
  {
    "id": "6a19dd531babc69aaa0e422e",
    "title": "England Phat Gorrilla Skyline Tee",
    "visible": true,
    "price_from": "£27.99",
    "price_to": "£27.99",
    "image": "https://images-api.printify.com/mockup/6a19dd531babc69aaa0e422e/12022/102006/england-graphic-tee-phat-gorilla-london-skyline-football-fan-shirt.jpg?camera_label=back-2",
    "buy_url": "/.netlify/functions/create-checkout-session?key=england-phat-gorrilla-world-cup-tee-gildan-5000-12022",
    "drop": "World Cup",
    "type": "T-Shirt",
    "colours": "England colours",
    "sizes": "Sizes shown at checkout",
    "offer": "A country-inspired England supporter tee with skyline attitude and rugged streetwear texture. Secure GBP checkout, printed and fulfilled by Printify."
  },
  {
    "id": "6a1b17819a524711b5034c0a",
    "title": "Portugal Phat Gorrilla World Cup Tee",
    "visible": true,
    "price_from": "£27.99",
    "price_to": "£27.99",
    "image": "https://images-api.printify.com/mockup/6a1b17819a524711b5034c0a/12100/92570/portugal-phat-gorrilla-world-cup-tee-gildan-5000.jpg?camera_label=front",
    "buy_url": "/.netlify/functions/create-checkout-session?key=portugal-phat-gorrilla-world-cup-tee-gildan-5000-12022",
    "drop": "World Cup",
    "type": "T-Shirt",
    "colours": "Portugal colours",
    "sizes": "Sizes shown at checkout",
    "offer": "Portugal supporter energy with bold Phat Gorrilla graphics and a vintage streetwear finish. Secure GBP checkout, printed and fulfilled by Printify."
  },
  {
    "id": "6a19dabc997906336605f3eb",
    "title": "Phat Gorrilla Logo Zip Hoodie — Luxury Gold Monogram Streetwear",
    "visible": false,
    "price_from": "£103.11",
    "price_to": "£103.11",
    "image": "https://images-api.printify.com/mockup/6a19dabc997906336605f3eb/63249/5051/phat-gorrilla-logo-zip-hoodie-luxury-gold-monogram-streetwear.jpg?camera_label=front",
    "buy_url": "#checkout-not-ready",
    "offer": "Checkout is being connected for this product. Selected artwork may use intentional rustic print texture."
  },
  {
    "id": "6a19d8c9c03728859b04044a",
    "title": "Relaxed Hoodie — Minimal Gold 'B' Monogram Hoodie",
    "visible": false,
    "price_from": "£74.15",
    "price_to": "£74.15",
    "image": "https://images-api.printify.com/mockup/6a19d8c9c03728859b04044a/115803/111733/relaxed-hoodie-minimal-gold-b-monogram-hoodie.jpg?camera_label=folded",
    "buy_url": "#checkout-not-ready",
    "offer": "Checkout is being connected for this product. Selected artwork may use intentional rustic print texture."
  },
  {
    "id": "6a19d7bbbc484b92020c4a98",
    "title": "Minimalist Logo Tee — Gold 'PG' Monogram Chest T-Shirt",
    "visible": false,
    "price_from": "£20.99",
    "price_to": "£27.99",
    "image": "https://images-api.printify.com/mockup/6a19d7bbbc484b92020c4a98/12124/102005/minimalist-logo-tee-gold-pg-monogram-chest-t-shirt.jpg?camera_label=front-2",
    "buy_url": "#checkout-not-ready",
    "offer": "Checkout is being connected for this product. Selected artwork may use intentional rustic print texture."
  },
  {
    "id": "6a18807721f4508fc9026c24",
    "title": "Wales Phat Gorrilla Graphic T-Shirt — Rugby/Football Fan Tee",
    "visible": false,
    "price_from": "£36.42",
    "price_to": "£45.02",
    "image": "https://images-api.printify.com/mockup/6a18807721f4508fc9026c24/73207/98446/wales-phat-gorilla-graphic-t-shirt-rugbyfootball-fan-tee.jpg?camera_label=back",
    "buy_url": "#checkout-not-ready",
    "offer": "Checkout is being connected for this product. Selected artwork may use intentional rustic print texture."
  },
  {
    "id": "6a1bd78ea2f3e94ff40d5d50",
    "title": "Brazil Phat Gorrilla World Cup Tee",
    "visible": true,
    "price_from": "£27.99",
    "price_to": "£27.99",
    "image": "https://images-api.printify.com/mockup/6a1bd78ea2f3e94ff40d5d50/12100/92570/brazil-phat-gorrilla-world-cup-tee-gildan-5000.jpg?camera_label=front",
    "buy_url": "/.netlify/functions/create-checkout-session?key=brazil-phat-gorrilla-world-cup-tee-gildan-5000-12100",
    "drop": "World Cup",
    "type": "T-Shirt",
    "colours": "Brazil colours",
    "sizes": "Sizes shown at checkout",
    "offer": "Brazil-inspired football streetwear with strong colour and gorilla attitude. Secure GBP checkout, printed and fulfilled by Printify."
  },
  {
    "id": "6a174b81318117fcbc050461",
    "title": "Gorilla King Green Graphic Tee",
    "visible": true,
    "price_from": "£27.99",
    "price_to": "£27.99",
    "image": "https://images-api.printify.com/mockup/6a174b81318117fcbc050461/12100/92570/gorilla-king-tee-green-streetwear-graphic-t-shirt-with-phat-design.jpg?camera_label=front",
    "buy_url": "/.netlify/functions/create-checkout-session?key=gorilla-king-tee-green-streetwear-graphic-t-shirt-with-phat-design-12100",
    "drop": "Main Drop",
    "type": "T-Shirt",
    "colours": "Green / Black",
    "sizes": "Sizes shown at checkout",
    "offer": "A loud gorilla graphic tee with green streetwear impact and strong front-print energy. Secure GBP checkout, printed and fulfilled by Printify."
  },
  {
    "id": "6a1749a0a63666767e0ea50a",
    "title": "Phat Gorrilla Heavyweight Hoodie",
    "visible": true,
    "price_from": "£39.99",
    "price_to": "£39.99",
    "image": "https://images-api.printify.com/mockup/6a1749a0a63666767e0ea50a/123966/111658/unisex-heavyweight-hooded-sweatshirt.jpg?camera_label=front",
    "buy_url": "/.netlify/functions/create-checkout-session?key=unisex-heavyweight-hooded-sweatshirt-123966",
    "drop": "Main Drop",
    "type": "Hoodie",
    "colours": "Drop colours",
    "sizes": "Sizes shown at checkout",
    "offer": "A heavier Phat Gorrilla layer for cooler days, streetwear fits and launch-season drops. Secure GBP checkout, printed and fulfilled by Printify."
  },
  {
    "id": "6a1746c375f5c394ef0a8281",
    "title": "Phat Gorrilla Heavy Cotton Tee",
    "visible": true,
    "price_from": "£27.99",
    "price_to": "£27.99",
    "image": "https://images-api.printify.com/mockup/6a1746c375f5c394ef0a8281/12100/92570/unisex-heavy-cotton-tee.jpg?camera_label=front",
    "buy_url": "/.netlify/functions/create-checkout-session?key=unisex-heavy-cotton-tee-12102",
    "drop": "Main Drop",
    "type": "T-Shirt",
    "colours": "Drop colours",
    "sizes": "Sizes shown at checkout",
    "offer": "A staple heavy cotton tee for the main Phat Gorrilla range. Secure GBP checkout, printed and fulfilled by Printify."
  },
  {
    "id": "6a17456d75f5c394ef0a8194",
    "title": "Retro Neon Gorilla Crewneck",
    "visible": true,
    "price_from": "£39.99",
    "price_to": "£39.99",
    "image": "https://images-api.printify.com/mockup/6a17456d75f5c394ef0a8194/25458/98502/gorilla-crewneck-sweatshirt-phat-gorilla-retro-neon-logo.jpg?camera_label=front",
    "buy_url": "/.netlify/functions/create-checkout-session?key=gorilla-crewneck-sweatshirt-phat-gorilla-retro-neon-logo-25458",
    "drop": "Main Drop",
    "type": "Sweatshirt",
    "colours": "Neon / Black",
    "sizes": "Sizes shown at checkout",
    "offer": "Retro neon logo energy on a clean crewneck shape for everyday streetwear. Secure GBP checkout, printed and fulfilled by Printify."
  },
  {
    "id": "6a173b4315c0ad1fc90f07c4",
    "title": "Phat Gorrilla Oversized Boxy Tee",
    "visible": true,
    "price_from": "£27.99",
    "price_to": "£27.99",
    "image": "https://images-api.printify.com/mockup/6a173b4315c0ad1fc90f07c4/103520/100285/unisex-oversized-boxy-tee.jpg?camera_label=front",
    "buy_url": "/.netlify/functions/create-checkout-session?key=unisex-oversized-boxy-tee-103520",
    "drop": "Main Drop",
    "type": "Oversized Tee",
    "colours": "Drop colours",
    "sizes": "Sizes shown at checkout",
    "offer": "A boxier oversized streetwear fit for a stronger silhouette and bigger brand feel. Secure GBP checkout, printed and fulfilled by Printify."
  },
  {
    "id": "6a17387f616126f69b0aec15",
    "title": "Phat Gorrilla Classic Heavy Tee",
    "visible": true,
    "price_from": "£27.99",
    "price_to": "£27.99",
    "image": "https://images-api.printify.com/mockup/6a17387f616126f69b0aec15/12124/92570/unisex-heavy-cotton-tee.jpg?camera_label=front",
    "buy_url": "/.netlify/functions/create-checkout-session?key=unisex-heavy-cotton-tee-12124",
    "drop": "Main Drop",
    "type": "T-Shirt",
    "colours": "Drop colours",
    "sizes": "Sizes shown at checkout",
    "offer": "A classic Phat Gorrilla tee built for bold everyday wear and clean product styling. Secure GBP checkout, printed and fulfilled by Printify."
  },
  {
    "id": "6a1730f7318117fcbc04f678",
    "title": "Phat Gorrilla Wall Art Poster",
    "visible": true,
    "price_from": "£27.99",
    "price_to": "£27.99",
    "image": "https://images-api.printify.com/mockup/6a1730f7318117fcbc04f678/70655/11328/paper-poster.jpg?camera_label=front",
    "buy_url": "/.netlify/functions/create-checkout-session?key=paper-poster-70655",
    "drop": "Brand Art",
    "type": "Poster",
    "colours": "Print artwork",
    "sizes": "Size shown at checkout",
    "offer": "Phat Gorrilla wall art for rooms, studios and launch supporters who want the brand off-body too. Secure GBP checkout, printed and fulfilled by Printify."
  }
];
